version: "3"
vars:
  K8S_NS: "velvet-vista"
  K8S_NS_DEV: "velvet-vista-dev"

tasks:
  build-and-push:
    cmds:
      - |
        VERSION_FILE="src/velvet_vista/__version__.py"
        VERSION=$(grep -o 'version = "[^"]*"' ${VERSION_FILE} | cut -d '"' -f 2)
        echo $VERSION
        TAG="${VERSION}-dev"
        cp -r src docker/
        docker build -t harbor.squid-ink.us/politeauthority/velvet-vista:${TAG} --no-cache docker/
        rm -rf docker/src
        docker push harbor.squid-ink.us/politeauthority/velvet-vista:${TAG}
    silent: True

  dev-deploy:
    cmds:
      - echo "Deploying Velvet Vist dev"
      - |
        kustomize build kubernetes-manifests/envs/dev | kubectl apply -f -
      - echo "Success"

  dev-cp:
    cmds:
      - |
        NS=$"{{.K8S_NS_DEV}}"
        POD=$(kubectl get pods -n ${NS} --no-headers --field-selector=status.phase=Running | cut -d' ' -f1)
        CONTAINER="velvet-vista"
        echo "Copying to pod $POD"
        kubectl cp -n ${NS} ./configs/dev-config.yaml ${POD}:/configs/config.yaml
        kubectl cp -n ${NS} ./src ${POD}:/app
        kubectl exec -it -c ${CONTAINER} -n ${NS} ${POD} -- /bin/velvet-vista-build
    silent: True

  dev-exec:
    cmds:
      - |
        NS=$"{{.K8S_NS_DEV}}"
        POD=$(kubectl get pods -n ${NS} --no-headers --field-selector=status.phase=Running | cut -d' ' -f1)
        echo $POD
        echo "Exec to pod $POD"
        kubectl exec -n ${NS} -it ${POD} -- sh
    silent: True
