apiVersion: apps/v1
kind: Deployment
metadata:
  name: velvet-vista
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velvet-vista
  template:
    metadata:
      labels:
        app: velvet-vista
    spec:
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: velvet-vista
          image: politeauthority/velvet-vista:latest
          command: ["tail", "-f", "/dev/null"]
          env:
            - name: SONARR_URL
              valueFrom:
                secretKeyRef:
                  key: SONARR_URL
                  name: velvet-vista-keys
            - name: SONNAR_API_KEY
              valueFrom:
                secretKeyRef:
                  key: SONNAR_API_KEY
                  name: velvet-vista-keys
